# Generated by Django 5.2.12 on 2026-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_supervisor_role'),
        ('projects', '0002_project_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='projects.skill'),
        ),
    ]
