# Generated by Django 5.2.12 on 2026-03-18 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('language', 'Langage'), ('framework', 'Framework'), ('tool', 'Outil'), ('methodology', 'Méthodologie')], max_length=20)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domain', models.CharField(choices=[('IA', 'Intelligence Artificielle'), ('Web', 'Développement Web'), ('Mobile', 'Développement Mobile'), ('DevOps', 'DevOps'), ('Cybersecurity', 'Cybersécurité'), ('DataScience', 'Data Science'), ('IoT', 'Internet des Objets'), ('Cloud', 'Cloud Computing'), ('Other', 'Autre')], max_length=20)),
                ('technologies', models.CharField(help_text='Comma-separated list', max_length=500)),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20)),
                ('duration', models.CharField(choices=[('1month', '1 mois'), ('2months', '2 mois'), ('3months', '3 mois'), ('6months', '6 mois')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.skill')),
            ],
            options={
                'db_table': 'project_skills',
                'unique_together': {('project', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.ProjectSkill', to='projects.skill'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='projects.project')),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
