# Generated by Django 6.0.3 on 2026-04-09 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('deadline', 'Date Limite'), ('interview', 'Entretien'), ('milestone', 'Jalon')], default='deadline', max_length=20)),
                ('date', models.DateTimeField()),
                ('is_global', models.BooleanField(default=False, help_text='If True, visible to all students (admin broadcasts).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
                ('user', models.ForeignKey(blank=True, help_text='Owner of a personal event. Null for global milestones.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
    ]
