# Generated by Django 5.2.12 on 2026-03-18 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('cv', 'CV'), ('cahier_charges', 'Cahier des charges'), ('report', 'Rapport'), ('other', 'Autre')], max_length=20)),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('extracted_text', models.TextField(blank=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
